instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
# 이미지를 업로드하자
from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tweet.urls')),
    path('', include('user.urls')),          
]

# 이미지 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweet/urls.py
# tweet/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'), # 127.0.0.1:8000 과 views.py 폴더의 home 함수 연결
    path('tweet/', views.tweet, name='tweet'), # 127.0.0.1:8000/tweet 과 views.py 폴더의 tweet 함수 연결
    path('tweet/delete/<int:id>',views.delete_tweet, name='delete-tweet'),
    path('tweet/<int:id>', views.detail_tweet, name='detail-tweet'),
    path('tweet/comment/<int:id>', views.write_comment, name='write-comment'),
    path('tweet/home/comment/<int:id>', views.write_home_comment, name='write-home-comment'),
    path('tweet/comment/delete/<int:id>', views.delete_comment, name='delete-comment'),
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    path('post-add/', views.post_add),
    path('post-edit/<int:id>', views.post_edit, name='post-edit'),
    path('tweet/recommend/', views.recommend_view, name='recommend-view'),
    path('tweet/home/<int:id>', views.user_follow, name='user-follow'),   
    path('tweet/<int:id>', views.write_comment, name='write-comment'), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('sign-up/', views.sign_up_view, name='sign-up'),
    path('sign-in/', views.sign_in_view, name='sign-in'),
    path('logout/', views.logout, name='logout'),
    path('user/', views.user_view, name='user-list'),
    path('profile/', views.profile, name='profile'),
    path('user/follow/<int:id>', views.user_follow, name='user-follow'),
    path('change_profile/', views.change_profile),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweet/models.py
# tweet/models.py
from django.db import models
from user.models import UserModel
from taggit.managers import TaggableManager

# Create your models here.
class TweetModel(models.Model):
    class Meta:
        db_table = "tweet"

    author = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    content = models.CharField(max_length=256)
    tags = TaggableManager(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to = "images/")
    
    
class TweetComment(models.Model):
    class Meta: 
        db_table = "comment"
        
    tweet = models.ForeignKey(TweetModel, on_delete=models.CASCADE)
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    comment = models.CharField(max_length=256)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    
    



     

tweet/views.py
from re import T
from urllib import request
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import TweetModel
from .models  import TweetComment
from user.models import UserModel
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, TemplateView
import random

# Create your views here.

def home(request):
    user = request.user.is_authenticated
    if user:
        return redirect('/tweet')
    else:
        return redirect('/sign-in')
    
def tweet (request):
    if request.method == 'GET':
        user = request.user.is_authenticated
        
        if user:
            all_tweet = TweetModel.objects.all().order_by('-created_at')
            all_comment = TweetComment.objects.all().order_by('-created_at')
            all_image = TweetComment.objects.all().order_by('-created_at')
            recommend_list = UserModel.objects.all().exclude(username=request.user.username).order_by('id')[:5]
            return render(request, 'tweet/home.html',{'tweet':all_tweet ,'comment':all_comment, 'image':all_image, 'recommend_list': recommend_list})
        else:
            return redirect('/sign-in')
        
    elif request.method == 'POST':
        user = request.user
        content = request.POST.get('my-content')
        tags = request.POST.get('tag','').split(',')
        image = request.FILES.get('image', '')
        if content == '':
            all_tweet = TweetModel.objects.all().order_by('-created_at')
            return render(request,'tweet/post-add.html',{'error':'글은 공백일 수 없습니다.','tweet':all_tweet})
        else:
            my_tweet = TweetModel.objects.create(author=user, content=content, image=image)
            for tag in tags:
                tag = tag.strip()
                if tag != '':
                    my_tweet.tags.add(tag)
            my_tweet.save()
            return redirect('/tweet')

@login_required
def detail_tweet(request, id):
    my_tweet = TweetModel.objects.get(id=id)
    tweet_comment = TweetComment.objects.filter(tweet_id=id).order_by('-created_at')
    return render(request,'tweet/tweet_detail.html',{'tweet':my_tweet,'comment':tweet_comment})


@login_required
def write_comment(request, id):
    if request.method == 'POST':
        comment = request.POST.get("comment","")
        current_tweet = TweetModel.objects.get(id=id)

        TC = TweetComment()
        TC.comment = comment
        TC.author = request.user
        TC.tweet = current_tweet
        TC.save()

        return redirect('/tweet/'+str(id))

def write_home_comment(request,id):
    if request.method == 'POST':
        comment = request.POST.get("comment","")
        current_tweet = TweetModel.objects.get(id=id)

        TC = TweetComment()
        TC.comment = comment
        TC.author = request.user
        TC.tweet = current_tweet
        TC.save()

        return redirect('/tweet/')
    
@login_required
def delete_comment(request, id):
    comment = TweetComment.objects.get(id=id)
    current_tweet = comment.tweet.id
    comment.delete()
    return redirect('/tweet/'+str(current_tweet))
    
@login_required
def delete_tweet(request,id):
    my_tweet = TweetModel.objects.get(id=id)
    my_tweet.delete()
    return redirect('/tweet')

class TagCloudTV(TemplateView):
    template_name = 'taggit/tag_cloud_view.html'


class TaggedObjectLV(ListView):
    template_name = 'taggit/tag_with_post.html'
    model = TweetModel

    def get_queryset(self):
        return TweetModel.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context
    
@login_required    
def post_add(request):
    return render(request, 'tweet/post-add.html') 

@login_required
def post_edit(request,id):
    my_tweet = TweetModel.objects.get(id=id)
    if request.method == "POST":
        my_tweet.content = request.POST['my-content']
        my_tweet.image = request.FILES['image']
        
        if my_tweet.content == '' or my_tweet.image == '':
            my_tweet = TweetModel.objects.all().order_by('-created_at')
            
            return render(request,'tweet/post-edit.html',{'error':'글은 공백일 수 없습니다.','tweet':my_tweet})
        
        my_tweet.save()
        return redirect('/tweet')
        
    else:
        return render(request,'tweet/post-edit.html',{'tweet':my_tweet})

@login_required
def recommend_view(request):
    if request.method == 'GET':
        # 사용자를 불러오기, exclude와 request.user.username 를 사용해서 '로그인 한 사용자'를 제외하기
        recommend_list = UserModel.objects.all().exclude(username=request.user.username)
        return render(request, 'tweet/home.html', {'recommend_list': recommend_list})
    
@login_required
def user_follow(request, id):
    me = request.user
    click_user = UserModel.objects.get(id=id)
    if me in click_user.followee.all():
        click_user.followee.remove(request.user)
    else:
        click_user.followee.add(request.user)
    return redirect('/tweet')

templates/tweet/home.html
{% extends 'base.html' %}
{% block title %}
Home
{% endblock %}
{% block content %}
<div class="main_body" , style="width: 1000px; margin: 0px auto 0px auto;"> 
    <!-- 왼쪽 컬럼-->
    <!-- 작성 된 글이 나오는 곳 -->
    <div class="left_body">
        {% for tw in tweet %}
        <div class="border feed_box">
            <div class="container1">
                <a class="navbar-brand1" href="/" style="text-decoration: none; color: inherit;">
                    <div style="display: flex; align-items: center; ">
                        <div class="profile_box">
                            <a href="/tweet/{{ tw.id }}">
                                {% if tw.author.profile %}
                                <img class="profileimage" src="{{ tw.author.profile.url }}">
                                {% else %}
                                <img class="profileimage"
                                    src="https://us.123rf.com/450wm/thesomeday123/thesomeday1231712/thesomeday123171200009/91087331-%EB%82%A8%EC%84%B1%EC%9D%84%EC%9C%84%ED%95%9C-%EA%B8%B0%EB%B3%B8-%EC%95%84%EB%B0%94%ED%83%80-%ED%94%84%EB%A1%9C%ED%95%84-%EC%95%84%EC%9D%B4%EC%BD%98-%ED%9A%8C%EC%83%89-%EC%82%AC%EC%A7%84-%EC%9E%90%EB%A6%AC-%ED%91%9C%EC%8B%9C-%EC%9E%90-%EC%9D%BC%EB%9F%AC%EC%8A%A4%ED%8A%B8-%EB%B2%A1%ED%84%B0.jpg?ver=6">
                                {% endif %}
                            </a>
                        </div>
                        
                        <div class="name_content">
                            <p class="feed_name_txtt">{{ tw.author }}
                                






                                {% if tw.author == user %}
                                <a href="/post-edit/{{ tw.id }}" class="fs-5" style="margin-left:250px; color: black;"><i class="bi bi-pencil"></i></a>
                                {% endif %}
                            </p>
                        </div>
                        
                    </div>
                </a>
            </div>
            <a href="/tweet/{{ tw.id }}">
                {% if tw.image %}
                <img class="feed_img " src="{{ tw.image.url }}">
                {% else %}
                <img class="feed_img "
                    src="https://blog.kakaocdn.net/dn/cEftca/btqAgU7ckZC/2JaB2RLUkvskP7TqowbTLk/img.png">
                {% endif %}
            </a>
            <div class="feed_icon">
                <div>
                    <span class="material-icons-outlined">
                        favorite_border
                    </span>
                    <span class="material-icons-outlined">
                        mode_comment
                    </span>
                    <span class="material-icons-outlined">
                        send
                    </span>
                </div>
                <div>
                    <span class="material-icons-outlined">
                        turned_in_not
                    </span>
                </div>
            </div>
            <div class="feed_like">
                <p class="feed_txt"> <b>좋아요 10개</b></p>
            </div>
            <div class="feed_content">
                <p class="feed_txt" > <b> {{ tw.author }} </b> {{ tw.content }}
                <div style="text-align: left">
                    <span style="font-size: small">{{ tw.updated_at|timesince }} 전</span>
                </div>
                </p>
                {% if tw.tags.all %}
                {% for tag in tw.tags.all %}
                <a style="text-decoration: none; color: inherit;" href="{% url 'tagged_object_list' tag.name %}">
                    #{{ tag.name }}
                </a>
                {% endfor %}
                <a style="text-decoration: none" href="{% url 'tag_cloud' %}"></a>
                {% endif %}
            </div>
            <div class="feed_reply">
                <div class="feed_reply">
                    {% for cm in tw.tweetcomment_set.all %}
                    <span class="feed_txt"> <b> {{ cm.author }} </b> {{ cm.comment }}</span>
                    {% endfor %}
                </div>
                <div class="blank"></div>               
                <form class="input-group mb-3" action="/tweet/home/comment/{{ tw.id }}" method="post">
                    {% csrf_token %}
                    <input type="text" class="form-control" id='comment' name='comment'
                        placeholder="댓글을 남겨주세요" />
                    <button class="btn btn-outline-secondary" type="submit">작성</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- 오른 쪽 컬럼-->
    <div class="right_body">
        <div class="feed_name" style="justify-content: space-between">
            <div style="display: flex; align-items: center; ">
                <div class="big_profile_box">
                    {% if user.profile %}
                    <img class="profile_img" src="{{ user.profile.url }}">
                    {% else %}
                    <img class="profile_img"
                        src="https://us.123rf.com/450wm/thesomeday123/thesomeday1231712/thesomeday123171200009/91087331-%EB%82%A8%EC%84%B1%EC%9D%84%EC%9C%84%ED%95%9C-%EA%B8%B0%EB%B3%B8-%EC%95%84%EB%B0%94%ED%83%80-%ED%94%84%EB%A1%9C%ED%95%84-%EC%95%84%EC%9D%B4%EC%BD%98-%ED%9A%8C%EC%83%89-%EC%82%AC%EC%A7%84-%EC%9E%90%EB%A6%AC-%ED%91%9C%EC%8B%9C-%EC%9E%90-%EC%9D%BC%EB%9F%AC%EC%8A%A4%ED%8A%B8-%EB%B2%A1%ED%84%B0.jpg?ver=6">
                    {% endif %}
                </div>
                <div class="name_content">
                    <span class="feed_name_txt"> {{ user.username }} </span>
                    <span class="name_content_txt"> {{ user.first_name }} </span>
                </div>
            </div>
        </div>
        <div class="recommend_box">
            <span style="color: gray"> 회원님을 위한 추천</span>
            {% if user.is_authenticated %}
            <span style="font-size: 12px;">
                <a style="text-decoration: none; color: inherit;" href="/user">모두 보기</a>
            </span>
            {% endif %}
        </div>
        <div>
            {% for rl in recommend_list %}
                <div class="feed_name" style="justify-content: space-between">
                    <div class="profile_box">
                        {% if rl.profile %}
                        <img class="profileimage" src="{{ rl.profile.url }}">
                        {% else %}
                        <img class="profileimage"
                            src="https://us.123rf.com/450wm/thesomeday123/thesomeday1231712/thesomeday123171200009/91087331-%EB%82%A8%EC%84%B1%EC%9D%84%EC%9C%84%ED%95%9C-%EA%B8%B0%EB%B3%B8-%EC%95%84%EB%B0%94%ED%83%80-%ED%94%84%EB%A1%9C%ED%95%84-%EC%95%84%EC%9D%B4%EC%BD%98-%ED%9A%8C%EC%83%89-%EC%82%AC%EC%A7%84-%EC%9E%90%EB%A6%AC-%ED%91%9C%EC%8B%9C-%EC%9E%90-%EC%9D%BC%EB%9F%AC%EC%8A%A4%ED%8A%B8-%EB%B2%A1%ED%84%B0.jpg?ver=6">
                        {% endif %}
                    </div>
                    <div class="name_contentt">
                        <span class="feed_name_txt"> {{ rl.username }} </span>
                        <span class="name_content_txt"> {{ rl.first_name }}</span>
                    </div>
                    <div>
                        {% if rl in user.follow.all %}
                        <a href="/tweet/home/{{ rl.id }}" class="link_txt"style="color:grey;">
                            팔로잉
                        </a>
                        {% else %}
                        <a href="/tweet/home/{{ rl.id }}" class="link_txt" >
                            팔로우
                        </a>
                        {% endif %}
                    </div>
                    
                </div>
                {% endfor %}
        </div>
    </div>
   
</div>
{% endblock %}

templates/tweet/post-add.html
{% extends 'base.html' %}
{% block title %}
Post Add
{% endblock %}
{% block postadd %}

<div class="postadd_body" style="margin-top:-4%;">
    <div class="modal_window">
        <div class="modal_title">
            <div class="modal_title_side"></div>
            <div style="margin: 5px"> 새 게시물 </div>
            <a href="/">
                <div class="modal_title_side">
                    <span id="close_modal" class="close_modal material-icons-outlined" style="font-size: 30px; color: black;">
                        close
                    </span>
                </div>
            </a>
        </div>
        <form action="/tweet/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal_image_content">
                <div class="modal_image_upload_content">
                    <div class="image_content">
                        <div class="image_upload_content">
                            <input id="image" type="file" name="image" multiple>
                        </div>
                    </div>

                </div>
                <div class="modal_content_write">
                    <div class="feed_name">
                        <div class="big_profile_box" style="margin: 5px 0px 0px 5px;">
                            {% if user.profile %}
                            <img id="input_user_profile" type="file" name="profile" class="profile_img" src="{{ user.profile.url }}">
                            {% else %}
                            <img id="input_user_profile" type="file" name="profile" class="profile_img" src="https://us.123rf.com/450wm/thesomeday123/thesomeday1231712/thesomeday123171200009/91087331-%EB%82%A8%EC%84%B1%EC%9D%84%EC%9C%84%ED%95%9C-%EA%B8%B0%EB%B3%B8-%EC%95%84%EB%B0%94%ED%83%80-%ED%94%84%EB%A1%9C%ED%95%84-%EC%95%84%EC%9D%B4%EC%BD%98-%ED%9A%8C%EC%83%89-%EC%82%AC%EC%A7%84-%EC%9E%90%EB%A6%AC-%ED%91%9C%EC%8B%9C-%EC%9E%90-%EC%9D%BC%EB%9F%AC%EC%8A%A4%ED%8A%B8-%EB%B2%A1%ED%84%B0.jpg?ver=6">
                            {% endif %}
                        </div>
                        <span id="input_user_id" class="feed_name_txt"> {{ user.username }} </span>
                    </div>
                    <div >
                        <textarea style="height: 330px" id="my-content" class="feed_content_textarea form-control col-sm-4" rows="10"
                            name='my-content' placeholder="내용을 입력하세요..."></textarea>
                    </div>
                    <div class="row">
                        <div class="col-sm-9" style=" margin-top:5%;">
                            <input type="text" class="form-control" name="tag" id="tag" placeholder="#" style="margin-left:7%; width:270px;" >
                        </div>
                    </div>
                    {% if error %}
                    <p style="color:red; margin:3% auto 0px auto">
                        {{ error }}
                    </p>
                    {% endif %}
                    <div style="width: 100%; text-align: center;">
                        <a class="nav-link" href="/home">
                            <button id="button_write_feed" type="submit" class="btn btn-primary" style="width: 268px">
                            공유하기</button>
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock postadd %}`

templates/tweet/post-edit.html
{% extends 'base.html' %}
{% block postedit %}
    
<div class="postadd_body" style="margin-top:-4%;">
    <div class="modal_window">
        <div class="modal_title">
            <div class="modal_title_side"></div>
            <div style="margin: 5px"> 게시물 수정 </div>
            <a href="/">
                <div class="modal_title_side">
                    <span id="close_modal" class="close_modal material-icons-outlined" style="font-size: 30px; color: black;">
                        close
                    </span>
                </div>
            </a>
        </div>
        <form action="/post-edit/{{tweet.id}}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal_image_content">
                <div class="modal_image_upload_content">
                    <div class="image_content">
                        <div class="cor">
                            {% if tweet.image %}
                            <img class="detail_feed_img " src="{{ tweet.image.url }}">
                            {% else %}
                            <img class="detail_feed_img " src="https://blog.kakaocdn.net/dn/cEftca/btqAgU7ckZC/2JaB2RLUkvskP7TqowbTLk/img.png">
                            {% endif %}
                            <input id="image" type="file" name="image" multiple style="padding-left:100px; margin-top:5%;" >
                        </div>
                    </div>

                </div>
                <div class="modal_content_write">
                    <div class="feed_name">
                        <div class="profile_box">
                            {% if tweet.author.profile %}
                            <img class="profileimage" src="{{ tweet.author.profile.url }}">
                            {% else %}
                            <img class="profileimage"
                                src="https://us.123rf.com/450wm/thesomeday123/thesomeday1231712/thesomeday123171200009/91087331-%EB%82%A8%EC%84%B1%EC%9D%84%EC%9C%84%ED%95%9C-%EA%B8%B0%EB%B3%B8-%EC%95%84%EB%B0%94%ED%83%80-%ED%94%84%EB%A1%9C%ED%95%84-%EC%95%84%EC%9D%B4%EC%BD%98-%ED%9A%8C%EC%83%89-%EC%82%AC%EC%A7%84-%EC%9E%90%EB%A6%AC-%ED%91%9C%EC%8B%9C-%EC%9E%90-%EC%9D%BC%EB%9F%AC%EC%8A%A4%ED%8A%B8-%EB%B2%A1%ED%84%B0.jpg?ver=6">
                            {% endif %}
                        </div>
                        <span id="input_user_id" class="feed_name_txt"> {{ tweet.author.username }} </span>
                    </div>
                    <div>
                        <textarea style="height: 330px" id="my-content" class="feed_content_textarea form-control col-sm-4" rows="10"
                            name='my-content' placeholder="내용을 입력하세요...">{{ tweet.content }}</textarea>
                    </div>
                    <div class="row">
                        <div class="col-sm-9" style="margin-top:5%;">
                            <input type="text" class="form-control" name="tag" id="tag" placeholder="#" style="margin-left:7%; width:270px;" >
                        </div>
                    </div>
                    {% if error %}
                    <p style="color:red; margin:3% auto 0px auto;">
                        {{ error }}
                    </p>
                    {% endif %}
                    <div style="width: 100%; text-align: center;">
                        <a class="nav-link" href="/home">
                            <button id="button_write_feed" type="submit" class="btn btn-primary" style="width: 268px">
                            수정하기</button>
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock postedit %}